# ErrorPlots_fun
# the real deal

#'@title error_bars
#'@description analysis of error bars for a variable
#'@param df name of the dataframe that you want to analyse.
#'@param x variable within the dataframe you want to bin over. Should be provided in the form 'df$x'
#'@param s sequence of values (generated by seq(x,y,z)) - optional input: if not provided it will be calculated automatically.
#'@return an 'error_bars.out' object which contains (i) a dataframe of useful summary variables, and (b) a dot plot showing the error bars.
#'@export

error_bars = function(df, x, s = NULL){
  # where df= the dataframe containing the  values
  # x = the variable to bin on (e.g. df$x)
  # s = a vector of cuts to split up the data by (this can also be generated automatically)
  
  # check the format of the variables:
  if (!missing(s)){
    if (!is.numeric(s))
      stop("'s' must be a numeric vector")
    if (length(s) < 3)
      stop("'s' must be at least 3 values long")
  }
  # create 's' vector if it is missing:
  if(missing(s)) {
    a = min(floor(df$x))
    b = max(ceiling(df$x))
    c = (b - a) / 10
    d = seq(a, b, c)
    s = d[2:length(d)]
  }
  
  # make a copy of the df to manipulate
  df.copy = df
  
  # create the bin_x
  df.copy$bin_x = cut(df$x, breaks = c(-Inf, s, Inf), 
                      labels = c(s, Inf))
  df.copy$bin_x <- as.numeric(as.character(df.copy$bin_x))
  
  # create the summary variables in df.summary:
  
  df.summary <- df.copy %>% 
    group_by(bin_x) %>%
    summarize(xmean = mean(x),
              ymin = min(y),
              ymax = max(y),
              ymean = mean(y),
              ysd = sd(y),
              ymean_plus_sd = mean(y) + sd(y),
              ymean_minus_sd = mean(y) - sd(y),
              yse = sd(y)/sqrt(length(y)),
              ymean_plus_se = mean(y) + sd(y)/sqrt(length(y)),
              ymean_minus_se = mean(y) - sd(y)/sqrt(length(y))
    )
  df.summary$bin_x <- as.numeric(as.character(df.summary$bin_x))
  df.summary$ynum = count(df.copy, bin_x)$n
  
  errorbars_plot = ggplot(df.summary, aes(bin_x, ymean)) +
    geom_point(size = 2) +
    geom_errorbar(aes(ymin = ymean_minus_sd, ymax = ymean_plus_sd, width=0.75, color= 'Standard Deviation')) +
    geom_errorbar(aes(ymin = ymean_minus_se, ymax = ymean_plus_se, width=0.75, color = 'Standard Error')) +
    labs(x = 'x bin', y = 'y values') +
    ggtitle('Plot of error bars') + 
    scale_colour_discrete(name="Measures") +
    theme_bw()
  
  
   
  error_bars.out = structure(list(plot = errorbars_plot,
                                  df.summary = df.summary,
                                  df = df.copy),
                             class = 'error_bars.object')
  
  return(error_bars.out)
}